apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grafana-internal-vikyath
  description: pipeline build and deploy
  annotations:
    harness.io/project-url: https://uat.harness.io/ng/account/I3TdrVLBSd2Zr2ttor7Z2A/cf/orgs/default/projects/HarnessFeatureFlags/
    grafana/dashboard-selector: "folderUrl == 'http://35.224.109.15:3000/dashboards/f/TSFz-KWIz/idp'"
    grafana/overview-dashboard: "http://35.224.109.15:3000/d/8j2vkDZSz/sample?orgId=1"
    grafana/alert-label-selector: "destination=sto-prod-slack"

  tags:
    - java

  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: team-cme
